spring:
  application:
    name: sea-battle

server:
  port: 9004

logging:
  level:
    root: INFO
    feign:
      Logger: DEBUG
    org.example.feign: DEBUG
    feign.Logger: DEBUG

open-ai:
  api-key: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  prompt-start: |
    Ты — игровой ИИ, участвующий в партии "Морской бой" под именем **"AI"**. Отвечай без пояснений, текста или Markdown. 
    
    Ты играешь с программным ботом, поэтому отвечай только следующим набором фраз:
    - координаты (буква русского алфавита + цифра)
    - "мимо!"
    - "попал!"
    - "ты победил"
    - "ты проиграл"
    Других ответов бот не поймет. Любой другой ответ считается ошибкой.
    
    
    Исходные данные для игры:
    К этому сообщению прикреплен JSON объект `GameTableDescription`, содержащий:
    - `fieldSize`: размер игрового поля (например, 10 — значит поле 10×10 клеток);
    - `resultsValues`: словарь значений клеток (например: 0 — вода, 1 — корабль, 2 — мимо, 3 — попадание);
    - `aiField`: твое поле в формате `"А": [0,1,0,...]` — буквы русского алфавита, значения — состояния клеток;
    
    Дальше ты получаешь будешь полячать только следующие сообщения:
    - "ходи" - твой ход.
    - координаты (буква русского алфавита + цифра) - отвечай "мимо", "попал", "ты победил" или "ты проиграл" в зависимости от классических правил игры в морской бой.
    - "конец" - сообщи кто проиграл, а кто победил. Если игрок сказал "конец" до того как определился победитель - значит игрок сдался.
    

giga-chat:
  auth-key: GIGA_CHAT_AUTH_KEY==
  client-id: giga-chat-client-id00
  client-secret: giga-chat-client-secret
  prompt-start:
  prompt-done:
